version: '2'
services:

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        ports:
            - "9090:9090"
        volumes:
            - $PWD:/etc/prometheus/

    consul:
        image: consul
        ports:
          - "8500:8500"

    springboot1:
        image: spring-boot-prometheus-demo:latest
        ports:
            - "8081:8080"
        environment:
          - server.port=8080

    springboot2:
        image: spring-boot-prometheus-demo:latest
        ports:
            - "8082:8080"
        environment:
          - server.port=8080          
