version: '2'
services:

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        volumes:
            - $PWD:/etc/prometheus
        ports:
            - "9090:9090"
        command:
            - "-config.file=/etc/prometheus/prometheus.yml"

    consul:
        image: consul
        ports:
          - "8500:8500"

    springboot1:
        image: springboot-prometheus-demo
        ports:
            - "8081:8080"
        environment:
          - server.port=8080

    springboot2:
        image: springboot-prometheus-demo
        ports:
            - "8082:8080"
        environment:
          - server.port=8080          