version: '2'
services:

    prometheus:
        image: prom/prometheus:latest
        volumes:
            - $PWD:/etc/prometheus
        ports:
            - "9090:9090"
        command:
            - "-config.file=/etc/prometheus/prometheus.yml"