version: '3'
services:

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        ports:
            - "9090:9090"
        volumes:
            - $PWD:/etc/prometheus/

    springboot:
        image: spring-boot-prometheus-demo
        container_name: spring-boot-prometheus-demo
        ports:
            - "8081:8080"        
        environment:
          - server.port=8080